services:
  ui:
    build: .
    ports:
      - "8188:8188"
    tty: true
    runtime: nvidia
    volumes:
      - ../ComfyUI:/app/ComfyUI
    working_dir: /app/ComfyUI
    user: user
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: /entrypoint.sh
