services:
  ui:
    build: .
    ports:
      - "8188:8188"
    tty: true
    runtime: nvidia
    shm_size: '4gb'
    volumes:
      - ../ComfyUI:/app/ComfyUI
      - ../sd-scripts:/app/sd-scripts
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: /entrypoint.sh
